# Generated by Django 5.1.1 on 2024-09-22 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkmovement',
            old_name='vehicle',
            new_name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='price_per_minute',
        ),
        migrations.RemoveField(
            model_name='parkmovement',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='parkmovement',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='parkmovement',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkmovement',
            name='entry_date',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkmovement',
            name='exit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='parkmovement',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='value',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.customer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='max_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ContractRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('until', models.IntegerField()),
                ('value', models.FloatField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.contract')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.customer')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.plan')),
            ],
        ),
    ]
