# Generated by Django 5.1.1 on 2024-09-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='in_parking',
            field=models.BooleanField(default=False),
        ),
    ]
