# Generated by Django 5.1.1 on 2024-09-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_vehicle_parkmovement_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
