# Generated by Django 5.1.1 on 2024-09-23 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_contract_description_alter_plan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerplan',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parkmovement',
            name='exit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
